resume_demo/main/urls.py
from django.urls import path
from . import views


app_name = "main"

urlpatterns = [
    path('',views.IndexView.as_view(),name="home"),
    path('contact/',views.ContactView.as_view(),name="contact"),
    path('portfolio/',views.PortfolioView.as_view(),name="portfolios"),
    path('portfolio/<slug:slug>',views.PortfolioDetailView.as_view(),name="portfolio"),
    path('blog/',views.BlogView.as_view(),name="blogs"),
    path('blog/<slug:slug>',views.BlogDetailView.as_view(),name="blogs"),
]

resume_demo/resume_demo/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls',namespace="main"))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


resume_demo/main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from ckeditor.fields import RichTextField


class Skill(models.Model):
    class Meta:
        verbose_name_plural = 'Skills'
        verbose_name = 'Skill'
    
    name = models.CharField(max_length=20, blank=True, null=True)
    score = models.IntegerField(default=80, blank=True, null=True)
    image = models.FileField(blank=True, null=True, upload_to="skills")
    is_key_skill = models.BooleanField(default=False)
    
    def __str__(self):
        return self.name

class UserProfile(models.Model):

    class Meta:
        verbose_name_plural = 'User Profiles'
        verbose_name = 'User Profile'
    
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(blank=True, null=True, upload_to="avatar")
    title = models.CharField(max_length=200, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    skills = models.ManyToManyField(Skill, blank=True)
    cv = models.FileField(blank=True, null=True, upload_to="cv")

    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name}'


class ContactProfile(models.Model):
    
    class Meta:
        verbose_name_plural = 'Contact Profiles'
        verbose_name = 'Contact Profile'
        ordering = ["timestamp"]
    timestamp = models.DateTimeField(auto_now_add=True)
    name = models.CharField(verbose_name="Name",max_length=100)
    email = models.EmailField(verbose_name="Email")
    message = models.TextField(verbose_name="Message")

    def __str__(self):
        return f'{self.name}'



class Testimonial(models.Model):

    class Meta:
        verbose_name_plural = 'Testimonials'
        verbose_name = 'Testimonial'
        ordering = ["name"]

    thumbnail = models.ImageField(blank=True, null=True, upload_to="testimonials")
    name = models.CharField(max_length=200, blank=True, null=True)
    role = models.CharField(max_length=200, blank=True, null=True)
    quote = models.CharField(max_length=500, blank=True, null=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class Media(models.Model):

    class Meta:
        verbose_name_plural = 'Media Files'
        verbose_name = 'Media'
        ordering = ["name"]
	
    image = models.ImageField(blank=True, null=True, upload_to="media")
    url = models.URLField(blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    is_image = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if self.url:
            self.is_image = False
        super(Media, self).save(*args, **kwargs)
    def __str__(self):
        return self.name

class Portfolio(models.Model):

    class Meta:
        verbose_name_plural = 'Portfolio Profiles'
        verbose_name = 'Portfolio'
        ordering = ["name"]
    date = models.DateTimeField(blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    body = RichTextField(blank=True, null=True)
    image = models.ImageField(blank=True, null=True, upload_to="portfolio")
    slug = models.SlugField(null=True, blank=True)
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Portfolio, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f"/portfolio/{self.slug}"


class Blog(models.Model):

    class Meta:
        verbose_name_plural = 'Blog Profiles'
        verbose_name = 'Blog'
        ordering = ["timestamp"]

    timestamp = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=200, blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    body = RichTextField(blank=True, null=True)
    slug = models.SlugField(null=True, blank=True)
    image = models.ImageField(blank=True, null=True, upload_to="blog")
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Blog, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f"/blog/{self.slug}"


class Certificate(models.Model):

    class Meta:
        verbose_name_plural = 'Certificates'
        verbose_name = 'Certificate'

    date = models.DateTimeField(blank=True, null=True)
    name = models.CharField(max_length=50, blank=True, null=True)
    title = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name


resume_demo/main/forms.py
from django import forms
from .models import ContactProfile


class ContactForm(forms.ModelForm):

	name = forms.CharField(max_length=100, required=True,
		widget=forms.TextInput(attrs={
			'placeholder': '*Full name..',

			}))
	email = forms.EmailField(max_length=254, required=True, 
		widget=forms.TextInput(attrs={
			'placeholder': '*Email..',

			}))
	message = forms.CharField(max_length=1000, required=True, 
		widget=forms.Textarea(attrs={
			'placeholder': '*Message..',
			'rows': 6,
			}))


	class Meta:
		model = ContactProfile
		fields = ('name', 'email', 'message',)

resume_demo/main/views.py
from django.shortcuts import render
from django.contrib import messages
from .models import (
		UserProfile,
		Blog,
		Portfolio,
		Testimonial,
		Certificate
	)

from django.views import generic


from . forms import ContactForm


class IndexView(generic.TemplateView):
	template_name = "main/index.html"

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		
		testimonials = Testimonial.objects.filter(is_active=True)
		certificates = Certificate.objects.filter(is_active=True)
		blogs = Blog.objects.filter(is_active=True)
		portfolio = Portfolio.objects.filter(is_active=True)
		
		context["testimonials"] = testimonials
		context["certificates"] = certificates
		context["blogs"] = blogs
		context["portfolio"] = portfolio
		return context


class ContactView(generic.FormView):
	template_name = "main/contact.html"
	form_class = ContactForm
	success_url = "/"
	
	def form_valid(self, form):
		form.save()
		messages.success(self.request, 'Thank you. We will be in touch soon.')
		return super().form_valid(form)


class PortfolioView(generic.ListView):
	model = Portfolio
	template_name = "main/portfolio.html"
	paginate_by = 10

	def get_queryset(self):
		return super().get_queryset().filter(is_active=True)


class PortfolioDetailView(generic.DetailView):
	model = Portfolio
	template_name = "main/portfolio-detail.html"

class BlogView(generic.ListView):
	model = Blog
	template_name = "main/blog.html"
	paginate_by = 10
	
	def get_queryset(self):
		return super().get_queryset().filter(is_active=True)


class BlogDetailView(generic.DetailView):
	model = Blog
	template_name = "main/blog-detail.html"

resume_demo/main/templates/main/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Resume</title>
    {% comment %} <meta name="author" content="Did Coding Limited & James Granger Design"> {% endcomment %}
    <link rel="canonical" href="{{request.path}}"/>
    <link rel="home" href="{% url 'main:home' %}"/>
    <meta name="description" content="{% block description %}{% endblock %}">
    <meta name="keywords" content="{% block keywords %}{% endblock %}">

    {% comment %} <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/icon.jpg' %}">
    <link rel="apple-touch-icon" type="image/jpg" href="{% static 'images/icon.jpg' %}"> {% endcomment %}

    <!-- ================================
    Start CSS
    ================================= -->
    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/swiper@7.0.5/swiper-bundle.min.css">
    <link href="{%static 'css/style.css' %}" rel="stylesheet">
    {% block extend_header %}{%endblock%}
    <!-- ================================
    End CSS
    ================================= -->

  </head>
  <body>
    {% include 'main/partials/messages.html'%}
    {% include 'main/partials/nav.html'%}
    
    {% block content %}{% endblock %}
    
    
    {% include 'main/partials/footer.html'%}

    <!-- ================================
    Start Scripts
    ================================= -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="js/bootstrap.bundle.min.js"></script>
    <script src="https://unpkg.com/swiper@7.0.5/swiper-bundle.min.js"></script>
    <script src="{% static 'js/script.js' %}"></script>
    {% block extend_footer %}{% endblock %}
    <!-- ================================
    End Scripts
    ================================= -->
  </body>
</html>

resume_demo/main/templates/main/blog-detail.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Did Coding - Blog Detail</title>
    <meta name="author" content="Did Coding Limited & James Granger Design">
    <link rel="canonical" href=""/>
    <link rel="home" href=""/>
    <meta name="description" content="">
    <meta name="keywords" content="">

    <!-- ================================
    Start CSS
    ================================= -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/swiper@7.0.5/swiper-bundle.min.css">
    <link href="css/style.css" rel="stylesheet">
    <!-- ================================
    End CSS
    ================================= -->

  </head>
  <body>

    <!-- ================================
    Start Navigation Bar
    ================================= -->
    <header>
      <div class="headerCol">
        <div class="container-fluid">
          <div class="row align-items-center">
            <div class="col-auto">
              <div class="logoCol"><a href="index.html"><img src="images/logo.png" alt="..."></a></div>
            </div>
            <div class="col">
              <div class="d-md-none">
                <button class="navToggle">
                  <span class="navToggle__text">Toggle Menu</span>
                </button>
              </div>
              <div class="navCollapseCol">
                <div class="navCol">
                  <ul>
                    <li><a href="index.html">Home</a></li>
                    <li><a href="portfolio.html">Portfolio</a></li>
                    <li><a href="blog.html">Blog</a></li>
                    <li><a href="contact.html">Contact</a></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </header>
    <!-- ================================
    End Navigation Bar
    ================================= -->

    <!-- ================================
    Start Content
    ================================= -->
    <section>
      <div class="innerPageBannerCol">
        <div class="container">
          <div class="row g-4 g-md-3  align-items-center">
            <div class="col-md-6">
              <div class="bannerContent">
                <h1 class="xlTitle pb-md-3">Blog title</h1>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-auto">
              <div class="authorCol">
                <h4 class="smTitle pb-3">Bobby Stearman</h4>
              </div>
            </div>
            <div class="col-md">
              <h4 class="smTitle pb-3">12-10-2021</h4>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section>
      <div class="sectionSpaceSm">
        <div class="container">
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
          Aenean congue imperdiet lorem ut posuere. Maecenas nec accumsan 
          risus, quis luctus libero. Morbi a nulla ac felis scelerisque 
          feugiat quis vitae turpis. Vivamus nec augue vel enim scelerisque 
          cursus. Curabitur efficitur ipsum quis turpis bibendum egestas. 
          Nunc ac euismod dolor. Vestibulum nec ipsum fermentum, semper 
          quam eu, porttitor elit. Maecenas efficitur ex eget augue euismod 
          semper. Curabitur pharetra tortor vel orci volutpat semper. 
          Donec feugiat mauris ante. In hac habitasse platea dictumst.
          </p>
        </div>
      </div>
    </section>
    <!-- ================================
    End Content
    ================================= -->
    
    <!-- ================================
    Start Footer
    ================================= -->
    <footer>
      <div class="footerCol">
        <div class="container">
          <ul class="socialCol">
            <li><a href="javascript:void(0)"><img src="images/fb.svg" alt="..."></a></li>
            <li><a href="javascript:void(0)"><img src="images/insta.svg" alt="..."></a></li>
            <li><a href="javascript:void(0)"><img src="images/twitter.svg" alt="..."></a></li>
            <li><a href="javascript:void(0)"><img src="images/linkedin.svg" alt="..."></a></li>
          </ul>
          <div class="copyrightCol">
            <p>Copyright ©2021 All rights reserved. Designed by <a href="https://jamesgrangerdesign.co.uk/" target="_blank">James Granger Design</a></p>
          </div>
        </div>
      </div>
    </footer>
    <!-- ================================
    End Footer
    ================================= -->

    <!-- ================================
    Start Scripts
    ================================= -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="js/bootstrap.bundle.min.js"></script>
    <script src="https://unpkg.com/swiper@7.0.5/swiper-bundle.min.js"></script>
    <script src="js/script.js"></script>
    <!-- ================================
    End Scripts
    ================================= -->
  </body>
</html>

resume_demo/main/templates/main/blog.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Did Coding - Blog</title>
    <meta name="author" content="Did Coding Limited & James Granger Design">
    <link rel="canonical" href=""/>
    <link rel="home" href=""/>
    <meta name="description" content="">
    <meta name="keywords" content="">

    <!-- ================================
    Start CSS
    ================================= -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/swiper@7.0.5/swiper-bundle.min.css">
    <link href="css/style.css" rel="stylesheet">
    <!-- ================================
    End CSS
    ================================= -->

  </head>
  <body>

    <!-- ================================
    Start Navigation Bar
    ================================= -->
    <header>
      <div class="headerCol">
        <div class="container-fluid">
          <div class="row align-items-center">
            <div class="col-auto">
              <div class="logoCol"><a href="index.html"><img src="images/logo.png" alt="..."></a></div>
            </div>
            <div class="col">
              <div class="d-md-none">
                <button class="navToggle">
                  <span class="navToggle__text">Toggle Menu</span>
                </button>
              </div>
              <div class="navCollapseCol">
                <div class="navCol">
                  <ul>
                    <li><a href="index.html">Home</a></li>
                    <li><a href="portfolio.html">Portfolio</a></li>
                    <li><a href="blog.html">Blog</a></li>
                    <li><a href="contact.html">Contact</a></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </header>
    <!-- ================================
    End Navigation Bar
    ================================= -->

    <!-- ================================
    Start Content
    ================================= -->
    <section>
      <div class="innerPageBannerCol">
        <div class="container">
          <div class="row g-4 g-md-3  align-items-center">
            <div class="col-md-6">
              <div class="bannerContent">
                <h1 class="xlTitle pb-md-3">See my recent blogs below</h1>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section>
      <div class="lightBg">
        <div class="container">
          <div class="portfolioContentMain">
            <div class="row g-3 g-md-4 g-lg-5 portfolioRow">
              <div class="col-md-6 pColMain">
                <div class="pCol">
                  <img src="images/project-img.jpg" alt="..." class="pImg">
                </div>
              </div>
              <div class="col-md-6 pColMain">
                <div class="pCol">
                  <img src="images/project-img.jpg" alt="..." class="pImg">
                </div>
              </div>
              <div class="col-md-6 pColMain">
                <div class="pCol">
                  <img src="images/project-img.jpg" alt="..." class="pImg">
                </div>
              </div>
              <div class="col-md-6 pColMain">
                <div class="pCol">
                  <img src="images/project-img.jpg" alt="..." class="pImg">
                </div>
              </div>
              <div class="col-md-6 pColMain">
                <div class="pCol">
                  <img src="images/project-img.jpg" alt="..." class="pImg">
                </div>
              </div>
              <div class="col-md-6 pColMain">
                <div class="pCol">
                  <img src="images/project-img.jpg" alt="..." class="pImg">
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- ================================
    End Content
    ================================= -->
    
    <!-- ================================
    Start Footer
    ================================= -->
    <footer>
      <div class="footerCol">
        <div class="container">
          <ul class="socialCol">
            <li><a href="javascript:void(0)"><img src="images/fb.svg" alt="..."></a></li>
            <li><a href="javascript:void(0)"><img src="images/insta.svg" alt="..."></a></li>
            <li><a href="javascript:void(0)"><img src="images/twitter.svg" alt="..."></a></li>
            <li><a href="javascript:void(0)"><img src="images/linkedin.svg" alt="..."></a></li>
          </ul>
          <div class="copyrightCol">
            <p>Copyright ©2021 All rights reserved. Designed by <a href="https://jamesgrangerdesign.co.uk/" target="_blank">James Granger Design</a></p>
          </div>
        </div>
      </div>
    </footer>
    <!-- ================================
    End Footer
    ================================= -->

    <!-- ================================
    Start Scripts
    ================================= -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="js/bootstrap.bundle.min.js"></script>
    <script src="https://unpkg.com/swiper@7.0.5/swiper-bundle.min.js"></script>
    <script src="js/script.js"></script>
    <!-- ================================
    End Scripts
    ================================= -->
  </body>
</html>

resume_demo/main/templates/main/contact.html
{% extends 'main/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}

<section>
  <div class="innerPageBannerCol">
    <div class="container">
      <div class="row g-4 g-md-3  align-items-center">
        <div class="col-md-6">
          <div class="bannerContent">
            <h1 class="xlTitle pb-md-3">Contact us below</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="lightBg">
    <div class="container">
        <form id="contactForm" method="POST" action="/contact/">
        {% csrf_token %}
            <label for="name">Name</label>
            {{form.name}}

            <label for="email">Email</label>
            {{form.email}}

            <label for="message">Message</label>
            {{form.message}}

            <input class='btn btnPrimary' type="submit" value="Submit">
        </form>
    </div>
  </div>
</section>
<!-- ================================
End Content
================================= -->
{%endblock%}
    

resume_demo/main/templates/main/partials/footer.html
{% load static %}
<!-- ================================
Start Footer
================================= -->
<footer>
    <div class="footerCol">
    <div class="container">
        <ul class="socialCol">
        <li><a href="https://www.facebook.com/login/"><img src="{% static 'images/fb.svg' %}" alt=""></a></li>
        <li><a href="https://www.instagram.com/accounts/login/"><img src="{% static 'images/insta.svg' %}" alt="..."></a></li>
        <li><a href="https://twitter.com/i/flow/login"><img src="{% static 'images/twitter.svg' %}" alt="..."></a></li>
        <li><a href="https://www.linkedin.com/home"><img src="{% static 'images/linkedin.svg' %}" alt="..."></a></li>
        </ul>
        <div class="copyrightCol">
        <p>Copyright ©{% now 'Y' %} All rights reserved . </a></p>
        </div>
    </div>
    </div>
</footer>
<!-- ================================
End Footer
================================= -->

resume_demo/main/templates/main/partials/messages.html
{% if messages %}
    {% for messages in messages %}
        {% if messages.tags %} <script>alert("{{message}}")</script> {% endif %}
    {% endfor %}
{% endif %}

resume_demo/main/templates/main/partials/nav.html
{% load static %}
<!-- ================================
Start Navigation Bar
================================= -->
<header>
    <div class="headerCol">
    <div class="container-fluid">
        <div class="row align-items-center">
        <div class="col-auto">
            {% comment %} <div class="logoCol"><a href="{% url 'main:home' %}"><img src="{% static 'images/logo.png' %}" alt="..."></a></div> {% endcomment %}
        </div>
        <div class="col">
            <div class="d-md-none">
            <button class="navToggle">
                <span class="navToggle__text">Toggle Menu</span>
            </button>
            </div>
            <div class="navCollapseCol">
            <div class="navCol">
                <ul>
                <li><a href="{%url 'main:home'%}">Home</a></li>
                <li><a href="{%url 'main:portfolios' %}">Portfolio</a></li>
                {% comment %} <li><a href="{% url 'main:blogs' %}">Blog</a></li> {% endcomment %}
                <li><a href="{%url 'main:contact'%}">Contact</a></li>
                </ul>
            </div>
            </div>
        </div>
        </div>
    </div>
    </div>
</header>
<!-- ================================
End Navigation Bar
================================= -->

resume_demo/main/templates/main/portfolio.html
{% extends 'main/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->


{% block content %}

<section>
  <div class="innerPageBannerCol">
    <div class="container">
      <div class="row g-4 g-md-3  align-items-center">
        <div class="col-md-6">
          <div class="bannerContent">
            <h1 class="xlTitle pb-md-3">See my recent projects below</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="lightBg">
    <div class="container">
      <div class="portfolioContentMain">
        <div class="row g-3 g-md-4 g-lg-5 portfolioRow">
          {% for obj in object_list %}
          <div class="col-md-6 pColMain">
            <div class="pCol">
              <a href="{% url 'main:portfolio' slug=obj.slug %}" >
              <img src="{{obj.image.url}}" alt="..." class="pImg">
              </a>
            </div>
          </div>
          {% endfor %}
          
        </div>
      </div>
    </div>
  </div>
</section>
<!-- ================================
End Content
================================= -->
{% endblock%}    